apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.artifactId}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.artifactId}
  minReplicas: ${jkube.configuratioon.min-replicas}
  maxReplicas: ${jkube.configuratioon.max-replicas}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
        - type: Pods
          value: 4
          periodSeconds: 15
      selectPolicy: Max
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: ${jkube.configuratioon.scale.cpu-usage}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: ${jkube.configuratioon.scale.memory-usage}
